---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart postgres
  ansible.builtin.systemd:
    name: "postgresql@{{ postgres_version }}-main"
    state: restarted
